//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurixfy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembresiaVW
    {
        public int MembresiaID { get; set; }
        public string Correo { get; set; }
        public string Pasword { get; set; }
        public System.DateTime FechaInicioM { get; set; }
        public System.DateTime FechaFinM { get; set; }
        public bool Activo { get; set; }
        public bool EsAdmin { get; set; }
        public bool Pago { get; set; }
        public Nullable<int> DiasFaltantes { get; set; }
    }
}
