//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurixfy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int NoticiaID { get; set; }
        public string NotaDesc { get; set; }
        public string Img { get; set; }
        public string Urls { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NomNotica { get; set; }
    }
}
