//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurixfy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pdf
    {
        public int PdfID { get; set; }
        public string NombrePdf { get; set; }
        public bool Activo { get; set; }
    }
}
